-- CONSOLIDATED SNAPTRIP INITIALIZATION SCRIPT
-- Run this in your Supabase SQL Editor

-- 0. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  updated_at timestamp with time zone DEFAULT now(),
  username text UNIQUE,
  full_name text,
  avatar_url text,
  website text,
  phone text,
  location text,
  bio text,
  preferences jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( (preferences->>'public_profile')::boolean = true OR auth.uid() = id );

CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id );

-- 2. Places Table (Quoted version from FRESH_START_PLACES.sql)
CREATE TABLE IF NOT EXISTS public.places (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" text NOT NULL,
  "city" text,
  "website" text,
  "title" text,
  "subTitle" text,
  "reviewsCount" bigint,
  "postalCode" text,
  "phone" text,
  "description" text,
  "categoryName" text,
  "address" text,
  "image_url" text,
  "location_lat" double precision,
  "location_lng" double precision,
  "openingHours_0_day" text, "openingHours_0_hours" text,
  "openingHours_1_day" text, "openingHours_1_hours" text,
  "openingHours_2_day" text, "openingHours_2_hours" text,
  "openingHours_3_day" text, "openingHours_3_hours" text,
  "openingHours_4_day" text, "openingHours_4_hours" text,
  "openingHours_5_day" text, "openingHours_5_hours" text,
  "openingHours_6_day" text, "openingHours_6_hours" text,
  "ai_Acc_0_entrance" boolean, "ai_Acc_1_entrance" boolean, "ai_Acc_2_entrance" boolean, "ai_Acc_3_entrance" boolean, "ai_Acc_4_entrance" boolean,
  "ai_Acc_0_parking" boolean, "ai_Acc_1_parking" boolean, "ai_Acc_2_parking" boolean, "ai_Acc_3_parking" boolean, "ai_Acc_4_parking" boolean,
  "ai_Acc_0_restroom" boolean, "ai_Acc_1_restroom" boolean, "ai_Acc_2_restroom" boolean, "ai_Acc_3_restroom" boolean, "ai_Acc_4_restroom" boolean,
  "ai_Chld_0_kids" boolean, "ai_Chld_1_kids" boolean, "ai_Chld_2_kids" boolean, "ai_Chld_3_kids" boolean,
  "ai_Crwd_0_lgbtq" boolean, "ai_Crwd_1_lgbtq" boolean, "ai_Crwd_2_lgbtq" boolean, "ai_Crwd_3_lgbtq" boolean,
  "ai_Pets_0_dogs" boolean, "ai_Pets_1_dogs" boolean, "ai_Pets_2_dogs" boolean,
  "ai_Plan_0_tickets" boolean, "ai_Plan_1_tickets" boolean, "ai_Plan_2_tickets" boolean, "ai_Plan_3_tickets" boolean,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE("title", "address")
);

CREATE INDEX IF NOT EXISTS idx_places_country ON places("country");
CREATE INDEX IF NOT EXISTS idx_places_city ON places("city");

-- 3. Trips Schema
CREATE TABLE IF NOT EXISTS public.trips (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  country text,
  style text,
  duration text,
  immersion text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own trips."
  ON public.trips FOR SELECT
  USING ( auth.uid() = user_id );

CREATE POLICY "Public trips are viewable by everyone if profile is public."
  ON public.trips FOR SELECT
  USING ( 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = trips.user_id 
      AND (profiles.preferences->>'public_profile')::boolean = true
    )
    OR auth.uid() = user_id
  );

CREATE POLICY "Users can insert their own trips."
  ON public.trips FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

CREATE POLICY "Users can update their own trips."
  ON public.trips FOR UPDATE
  USING ( auth.uid() = user_id );

CREATE POLICY "Users can delete their own trips."
  ON public.trips FOR DELETE
  USING ( auth.uid() = user_id );

-- Trip Days
CREATE TABLE IF NOT EXISTS public.trip_days (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  trip_id uuid REFERENCES public.trips(id) ON DELETE CASCADE NOT NULL,
  day_index integer NOT NULL,
  title text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.trip_days ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view days of their own trips."
  ON public.trip_days FOR SELECT
  USING ( EXISTS ( SELECT 1 FROM trips WHERE trips.id = trip_days.trip_id AND trips.user_id = auth.uid() ) );

CREATE POLICY "Users can insert days for their own trips."
  ON public.trip_days FOR INSERT
  WITH CHECK ( EXISTS ( SELECT 1 FROM trips WHERE trips.id = trip_days.trip_id AND trips.user_id = auth.uid() ) );

-- Trip Items
CREATE TABLE IF NOT EXISTS public.trip_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  day_id uuid REFERENCES public.trip_days(id) ON DELETE CASCADE NOT NULL,
  place_id bigint REFERENCES public.places(id),
  custom_name text,
  order_index integer NOT NULL,
  note text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.trip_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view items of their own trips."
  ON public.trip_items FOR SELECT
  USING ( EXISTS ( SELECT 1 FROM trip_days JOIN trips ON trip_days.trip_id = trips.id WHERE trip_days.id = trip_items.day_id AND trips.user_id = auth.uid() ) );

CREATE POLICY "Users can insert items for their own trips."
  ON public.trip_items FOR INSERT
  WITH CHECK ( EXISTS ( SELECT 1 FROM trip_days JOIN trips ON trip_days.trip_id = trips.id WHERE trip_days.id = trip_items.day_id AND trips.user_id = auth.uid() ) );

-- 4. Geographic Tables
CREATE TABLE IF NOT EXISTS public.countries (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  iso3 char(3),
  iso2 char(2),
  phone_code text,
  capital text,
  currency text,
  native text,
  emoji text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.states (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  country_id bigint REFERENCES public.countries(id) ON DELETE CASCADE,
  state_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cities (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  state_id bigint REFERENCES public.states(id) ON DELETE CASCADE,
  country_id bigint REFERENCES public.countries(id) ON DELETE CASCADE,
  latitude decimal(10, 8),
  longitude decimal(11, 8),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_countries_name ON countries(name);
CREATE INDEX IF NOT EXISTS idx_states_name ON states(name);
CREATE INDEX IF NOT EXISTS idx_cities_name ON cities(name);

-- 5. Traveler Reviews
CREATE TABLE IF NOT EXISTS public.traveler_reviews (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  country text NOT NULL,
  selected_cities text[] DEFAULT '{}',
  sightseeing_rating integer CHECK (sightseeing_rating BETWEEN 1 AND 5),
  local_people_rating integer CHECK (local_people_rating BETWEEN 1 AND 5),
  service_quality_rating integer CHECK (service_quality_rating BETWEEN 1 AND 5),
  safety_rating integer CHECK (safety_rating BETWEEN 1 AND 5),
  price_rating integer CHECK (price_rating BETWEEN 1 AND 5),
  review_text text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.traveler_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public reviews are viewable by everyone if profile is public."
  ON public.traveler_reviews FOR SELECT
  USING ( 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = traveler_reviews.user_id 
      AND (profiles.preferences->>'public_profile')::boolean = true
    )
    OR auth.uid() = user_id
  );

-- 6. Functions and Triggers
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Force schema reload
NOTIFY pgrst, 'reload schema';
