-- Migration to create the places table for Google Places sync

create table if not exists places (
  id bigint generated by default as identity primary key,
  country text not null,
  city text,
  website text,
  title text,
  "subTitle" text,
  "reviewsCount" bigint,
  "postalCode" text,
  phone text,
  description text,
  "categoryName" text,
  address text,
  
  -- Location
  location_lat double precision,
  location_lng double precision,

  -- Opening Hours (0-6)
  openingHours_0_day text, openingHours_0_hours text,
  openingHours_1_day text, openingHours_1_hours text,
  openingHours_2_day text, openingHours_2_hours text,
  openingHours_3_day text, openingHours_3_hours text,
  openingHours_4_day text, openingHours_4_hours text,
  openingHours_5_day text, openingHours_5_hours text,
  openingHours_6_day text, openingHours_6_hours text,

  -- Accessibility (0-4)
  "additionalInfo_Accessibility_0_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_entrance" boolean,
  
  "additionalInfo_Accessibility_0_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_parking_lot" boolean,
  
  "additionalInfo_Accessibility_0_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_restroom" boolean,

  -- Children (0-3)
  "additionalInfo_Children_0_Good_for_kids" boolean,
  "additionalInfo_Children_1_Good_for_kids" boolean,
  "additionalInfo_Children_2_Good_for_kids" boolean,
  "additionalInfo_Children_3_Good_for_kids" boolean,

  -- Crowd (0-3)
  "additionalInfo_Crowd_0_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_1_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_2_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_3_LGBTQ+_friendly" boolean,

  -- Pets (0-2)
  "additionalInfo_Pets_0_Dogs_allowed" boolean,
  "additionalInfo_Pets_1_Dogs_allowed" boolean,
  "additionalInfo_Pets_2_Dogs_allowed" boolean,

  -- Planning (0-3)
  "additionalInfo_Planning_0_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_1_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_2_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_3_Getting_tickets_in_advance_recommended" boolean,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Ensure unique title and address to prevent duplicates
  unique(title, address)
);

-- Index for country searches
create index if not exists idx_places_country on places(country);
create index if not exists idx_places_city on places(city);
-- Migration to create the places table for Google Places sync (Shortened names to avoid PostgreSQL 63-char limit)

create table if not exists places (
  id bigint generated by default as identity primary key,
  country text not null,
  city text,
  website text,
  title text,
  "subTitle" text,
  "reviewsCount" bigint,
  "postalCode" text,
  phone text,
  description text,
  "categoryName" text,
  address text,
  
  -- Location
  location_lat double precision,
  location_lng double precision,

  -- Opening Hours (0-6)
  openingHours_0_day text, openingHours_0_hours text,
  openingHours_1_day text, openingHours_1_hours text,
  openingHours_2_day text, openingHours_2_hours text,
  openingHours_3_day text, openingHours_3_hours text,
  openingHours_4_day text, openingHours_4_hours text,
  openingHours_5_day text, openingHours_5_hours text,
  openingHours_6_day text, openingHours_6_hours text,

  -- Accessibility (ai_Acc)
  "ai_Acc_0_entrance" boolean,
  "ai_Acc_1_entrance" boolean,
  "ai_Acc_2_entrance" boolean,
  "ai_Acc_3_entrance" boolean,
  "ai_Acc_4_entrance" boolean,
  
  "ai_Acc_0_parking" boolean,
  "ai_Acc_1_parking" boolean,
  "ai_Acc_2_parking" boolean,
  "ai_Acc_3_parking" boolean,
  "ai_Acc_4_parking" boolean,
  
  "ai_Acc_0_restroom" boolean,
  "ai_Acc_1_restroom" boolean,
  "ai_Acc_2_restroom" boolean,
  "ai_Acc_3_restroom" boolean,
  "ai_Acc_4_restroom" boolean,

  -- Children (ai_Chld)
  "ai_Chld_0_kids" boolean,
  "ai_Chld_1_kids" boolean,
  "ai_Chld_2_kids" boolean,
  "ai_Chld_3_kids" boolean,

  -- Crowd (ai_Crwd)
  "ai_Crwd_0_lgbtq" boolean,
  "ai_Crwd_1_lgbtq" boolean,
  "ai_Crwd_2_lgbtq" boolean,
  "ai_Crwd_3_lgbtq" boolean,

  -- Pets (ai_Pets)
  "ai_Pets_0_dogs" boolean,
  "ai_Pets_1_dogs" boolean,
  "ai_Pets_2_dogs" boolean,

  -- Planning (ai_Plan)
  "ai_Plan_0_tickets" boolean,
  "ai_Plan_1_tickets" boolean,
  "ai_Plan_2_tickets" boolean,
  "ai_Plan_3_tickets" boolean,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Ensure unique title and address to prevent duplicates
  unique(title, address)
);

-- Index for country searches
create index if not exists idx_places_country on places(country);
create index if not exists idx_places_city on places(city);
-- Create destinations table for rich content
create table destinations (
  id uuid default uuid_generate_v4() primary key,
  name text not null, -- Matches 'country' or 'city' in places
  type text not null, -- 'country', 'state'
  
  -- Rich Content Fields
  overview text,
  bucket_list jsonb, -- Array of { text, image_url }
  local_foods jsonb, -- Array of { name, description, image_url }
  local_phrases jsonb, -- Array of { phrase, translation, pronunciation }
  transportation_info text,
  
  cover_image_url text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(name, type)
);

-- Index for faster lookups
create index idx_destinations_name on destinations(name);

-- Force schema reload
NOTIFY pgrst, 'reload schema';
INSERT INTO destinations (name, type, overview, bucket_list, local_foods, local_phrases, transportation_info, cover_image_url)
VALUES (
  'Ireland',
  'country',
  'Ireland is a land of myth and legend, known for its lush green landscapes, rugged coastlines, and warm hospitality. From the bustling streets of Dublin to the serene beauty of the Wild Atlantic Way, it offers a rich blend of history, culture, and nature.',
  '[
    {"text": "Visit the Cliffs of Moher", "image_url": "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7"},
    {"text": "Kiss the Blarney Stone", "image_url": null},
    {"text": "Drive the Ring of Kerry", "image_url": null}
  ]'::jsonb,
  '[
    {"name": "Irish Stew", "description": "A hearty stew made with lamb, potatoes, carrots, and onions.", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Irish_stew_2009.jpg/800px-Irish_stew_2009.jpg"},
    {"name": "Soda Bread", "description": "A dense, unleavened bread made with baking soda.", "image_url": null}
  ]'::jsonb,
  '[
    {"phrase": "Dia dhuit", "translation": "Hello", "pronunciation": "dee-a gwitch"},
    {"phrase": "Sláinte", "translation": "Cheers", "pronunciation": "slawn-cha"}
  ]'::jsonb,
  'Public transport (buses and trains) connects major cities. For rural areas, renting a car is highly recommended to explore at your own pace.',
  'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7'
)
ON CONFLICT (name, type) DO UPDATE SET
  overview = EXCLUDED.overview,
  bucket_list = EXCLUDED.bucket_list,
  local_foods = EXCLUDED.local_foods,
  local_phrases = EXCLUDED.local_phrases,
  transportation_info = EXCLUDED.transportation_info,
  cover_image_url = EXCLUDED.cover_image_url;
-- Create a table for public profiles (optional but good practice)
create table profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  primary key (id),
  unique(username),
  constraint username_length check (char_length(username) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create trips table
create table trips (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  title text not null,
  country text,
  style text,
  duration text,
  immersion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table trips enable row level security;

create policy "Users can view their own trips."
  on trips for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own trips."
  on trips for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own trips."
  on trips for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own trips."
  on trips for delete
  using ( auth.uid() = user_id );

-- Create trip_days table
create table trip_days (
  id uuid default gen_random_uuid() primary key,
  trip_id uuid references trips(id) on delete cascade not null,
  day_index integer not null, -- 0 for Day 1, etc.
  title text, -- e.g. "Day 1", "Day 2"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table trip_days enable row level security;

create policy "Users can view days of their own trips."
  on trip_days for select
  using ( exists ( select 1 from trips where trips.id = trip_days.trip_id and trips.user_id = auth.uid() ) );

create policy "Users can insert days for their own trips."
  on trip_days for insert
  with check ( exists ( select 1 from trips where trips.id = trip_days.trip_id and trips.user_id = auth.uid() ) );

create policy "Users can update days for their own trips."
    on trip_days for update
    using ( exists ( select 1 from trips where trips.id = trip_days.trip_id and trips.user_id = auth.uid() ) );

create policy "Users can delete days for their own trips."
    on trip_days for delete
    using ( exists ( select 1 from trips where trips.id = trip_days.trip_id and trips.user_id = auth.uid() ) );


-- Create trip_items table
create table trip_items (
  id uuid default gen_random_uuid() primary key,
  day_id uuid references trip_days(id) on delete cascade not null,
  place_id bigint references places(id), -- Nullable if it's a custom item, but linking to places here
  custom_name text, -- If place_id is null or to override? Let's just use it for now.
  order_index integer not null,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table trip_items enable row level security;

create policy "Users can view items of their own trips."
  on trip_items for select
  using ( exists ( select 1 from trip_days join trips on trip_days.trip_id = trips.id where trip_days.id = trip_items.day_id and trips.user_id = auth.uid() ) );

create policy "Users can insert items for their own trips."
  on trip_items for insert
  with check ( exists ( select 1 from trip_days join trips on trip_days.trip_id = trips.id where trip_days.id = trip_items.day_id and trips.user_id = auth.uid() ) );

create policy "Users can update items for their own trips."
    on trip_items for update
    using ( exists ( select 1 from trip_days join trips on trip_days.trip_id = trips.id where trip_days.id = trip_items.day_id and trips.user_id = auth.uid() ) );

create policy "Users can delete items for their own trips."
    on trip_items for delete
    using ( exists ( select 1 from trip_days join trips on trip_days.trip_id = trips.id where trip_days.id = trip_items.day_id and trips.user_id = auth.uid() ) );

-- Function to handle new user profile creation automatically
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
-- Add email and password columns to profiles if they don't exist
-- WARNING: Storing passwords in plain text is a security risk. This is done per user request.
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'email') THEN 
        ALTER TABLE public.profiles ADD COLUMN email text;
    END IF; 
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'password') THEN 
        ALTER TABLE public.profiles ADD COLUMN password text;
    END IF;
END $$;

-- Update the handle_new_user trigger function to include email
-- Note: Triggers on auth.users CANNOT access the raw password as it is hashed before insert.
-- Therefore, the password must be synced from the client side (AuthModal).
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, email)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url',
    new.email
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    email = EXCLUDED.email,
    updated_at = NOW();
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- Add missing fields to profiles table
alter table public.profiles
  add column if not exists phone text,
  add column if not exists location text,
  add column if not exists bio text;

-- Force schema reload
NOTIFY pgrst, 'reload schema';
-- Create traveler_reviews table
create table traveler_reviews (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  country text not null,
  selected_cities text[] default '{}',
  sightseeing_rating integer check (sightseeing_rating between 1 and 5),
  local_people_rating integer check (local_people_rating between 1 and 5),
  service_quality_rating integer check (service_quality_rating between 1 and 5),
  safety_rating integer check (safety_rating between 1 and 5),
  price_rating integer check (price_rating between 1 and 5),
  review_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes
create index idx_traveler_reviews_user_id on traveler_reviews(user_id);
create index idx_traveler_reviews_country on traveler_reviews(country);

-- Force schema reload
NOTIFY pgrst, 'reload schema';

-- Allow public read access to traveler_reviews for Chart Map stats
create policy "Allow public read access to traveler_reviews"
  on traveler_reviews for select
  using ( true );

-- Ensure authenticated users can still insert
-- (The original creation script might have missed this or it's restricted)
create policy "Users can insert their own reviews"
  on traveler_reviews for insert
  with check ( auth.uid() = user_id );

-- Force schema reload
NOTIFY pgrst, 'reload schema';

-- Add preferences column to profiles
alter table public.profiles
  add column if not exists preferences jsonb default '{}'::jsonb;

-- Force schema reload
NOTIFY pgrst, 'reload schema';

-- 1. Profiles Table Policies
-- Enable RLS (just in case)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow users to insert their own profile
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can insert own profile'
    ) THEN
        CREATE POLICY "Users can insert own profile" 
        ON public.profiles 
        FOR INSERT 
        WITH CHECK (auth.uid() = id);
    END IF;
END $$;

-- Allow users to update their own profile
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can update own profile'
    ) THEN
        CREATE POLICY "Users can update own profile" 
        ON public.profiles 
        FOR UPDATE 
        USING (auth.uid() = id)
        WITH CHECK (auth.uid() = id);
    END IF;
END $$;

-- Allow users to view their own profile (and maybe others)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Profiles are viewable by everyone'
    ) THEN
        CREATE POLICY "Profiles are viewable by everyone" 
        ON public.profiles 
        FOR SELECT 
        USING (true);
    END IF;
END $$;

-- 2. Storage Policies for 'avatars' bucket
-- Ensure bucket exists and is public
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Policy to allow users to upload their own avatar
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Avatar upload policy'
    ) THEN
        CREATE POLICY "Avatar upload policy"
        ON storage.objects
        FOR INSERT
        WITH CHECK (
            bucket_id = 'avatars' 
            AND (storage.foldername(name))[1] = 'avatars'
        );
    END IF;
END $$;

-- Policy to allow users to update their own avatar
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Avatar update policy'
    ) THEN
        CREATE POLICY "Avatar update policy"
        ON storage.objects
        FOR UPDATE
        USING (
            bucket_id = 'avatars' 
            AND (storage.foldername(name))[1] = 'avatars'
        );
    END IF;
END $$;

-- Policy to allow public access to avatars
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE schemaname = 'storage' AND tablename = 'objects' AND policyname = 'Avatar public access'
    ) THEN
        CREATE POLICY "Avatar public access"
        ON storage.objects
        FOR SELECT
        USING (bucket_id = 'avatars');
    END IF;
END $$;
-- Add preferences column to profiles table
alter table public.profiles
  add column if not exists preferences jsonb default '{"email_notifications": true, "travel_recommendations": true, "public_profile": true}'::jsonb;

-- Force schema reload
NOTIFY pgrst, 'reload schema';
-- Ensure username is present and unique
-- For existing users without a username, we generate one from full_name or id
update public.profiles
set username = lower(regexp_replace(coalesce(full_name, 'traveler'), '[^a-zA-Z0-9]+', '-', 'g')) || '-' || substr(id::text, 1, 4)
where username is null;

-- Update RLS for profiles: Everyone can see basic info if public_profile is true
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( (preferences->>'public_profile')::boolean = true or auth.uid() = id );

-- Update RLS for trips: Everyone can see trips if the profile is public
create policy "Public trips are viewable by everyone if profile is public."
  on public.trips for select
  using ( 
    exists (
      select 1 from public.profiles 
      where profiles.id = trips.user_id 
      and (profiles.preferences->>'public_profile')::boolean = true
    )
    or auth.uid() = user_id
  );

-- Update RLS for traveler_reviews (used for stats)
create policy "Public reviews are viewable by everyone if profile is public."
  on public.traveler_reviews for select
  using ( 
    exists (
      select 1 from public.profiles 
      where profiles.id = traveler_reviews.user_id 
      and (profiles.preferences->>'public_profile')::boolean = true
    )
    or auth.uid() = user_id
  );
-- Add unique constraint and index for usernames
ALTER TABLE public.profiles ADD CONSTRAINT profiles_username_unique UNIQUE (username);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles (username);
-- Migration to create geographic lookup tables

-- 1. Countries table
create table countries (
  id bigint primary key,
  name text not null,
  iso3 char(3),
  iso2 char(2),
  phone_code text,
  capital text,
  currency text,
  native text,
  emoji text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 2. States table
create table states (
  id bigint primary key,
  name text not null,
  country_id bigint references countries(id) on delete cascade,
  state_code text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. Cities table
create table cities (
  id bigint primary key,
  name text not null,
  state_id bigint references states(id) on delete cascade,
  country_id bigint references countries(id) on delete cascade,
  latitude decimal(10, 8),
  longitude decimal(11, 8),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Indexes for performance
create index idx_countries_name on countries(name);
create index idx_states_name on states(name);
create index idx_cities_name on cities(name);
create index idx_cities_country_id on cities(country_id);
create index idx_cities_state_id on cities(state_id);

-- Force schema reload
NOTIFY pgrst, 'reload schema';
ALTER TABLE public.home_carousel
ADD COLUMN small_card_1_title text,
ADD COLUMN small_card_1_image text,
ADD COLUMN small_card_2_title text,
ADD COLUMN small_card_2_image text;

NOTIFY pgrst, 'reload schema';
-- 1. Create blogs table
CREATE TABLE IF NOT EXISTS public.blogs (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text not null unique,
  excerpt text not null,
  content text not null,
  category text not null,
  read_time text not null,
  image_url text not null,
  status text not null default 'Published',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- If the table already exists, run this to add the column:
-- ALTER TABLE public.blogs ADD COLUMN IF NOT EXISTS status text not null default 'Published';

-- 2. Enable RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- 3. Select policy (allow everyone to read blogs)
DROP POLICY IF EXISTS "Allow public read access to blogs" ON public.blogs;
CREATE POLICY "Allow public read access to blogs"
  ON public.blogs FOR SELECT
  USING (true);

-- 4. Write policy (allow authenticated users to manage blogs)
DROP POLICY IF EXISTS "Allow authenticated users to manage blogs" ON public.blogs;
CREATE POLICY "Allow authenticated users to manage blogs"
  ON public.blogs FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 5. Seed initial data
INSERT INTO public.blogs (title, slug, excerpt, content, category, read_time, image_url)
VALUES 
(
  'Hidden Gems in the Mediterranean',
  'hidden-gems-mediterranean',
  'Discover secret beaches, charming villages, and authentic local experiences away from tourist crowds.',
  '<p>The Mediterranean is home to some of the world''s most famous destinations, but beyond the crowded streets of Santorini and the bustling beaches of the Amalfi Coast lie hidden gems waiting to be discovered.</p><h2>1. Procida, Italy</h2><p>While neighboring Capri and Ischia get most of the attention, Procida remains a colorful, authentic escape. Its pastel-hued houses and quiet marinas offer a glimpse into traditional Italian island life.</p><h2>2. Kas, Turkey</h2><p>Nestled on Turkey''s turquoise coast, Kas is a bohemian paradise. It''s famous for its crystal-clear waters, ancient ruins, and a vibrant local market that comes alive every week.</p><h2>3. Mellieha, Malta</h2><p>Mellieha offers some of the best beaches in Malta, along with stunning views of the countryside. It''s the perfect spot for those looking to combine relaxation with historical exploration.</p>',
  'Destinations',
  '5 min read',
  'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=800&auto=format&fit=crop'
),
(
  'Budget Travel: Europe on $50/Day',
  'budget-travel-europe',
  'Learn how to explore Europe without breaking the bank with our expert money-saving tips and tricks.',
  '<p>Europe doesn''t have to be expensive. With a bit of planning and some insider knowledge, you can explore the continent''s most beautiful cities on a modest budget.</p><h2>Travel Off-Season</h2><p>Prices for accommodation and flights drop significantly outside of the peak summer months. Consider visiting in spring or autumn for a more affordable and less crowded experience.</p><h2>Use Public Transport</h2><p>Europe has some of the best public transport networks in the world. Instead of taxis or car rentals, use trains, buses, and metro systems to get around.</p><h2>Eat Like a Local</h2><p>Avoid restaurants in tourist hotspots. Instead, explore local markets and backstreet bistros where you can find delicious, authentic food at a fraction of the cost.</p>',
  'Travel Tips',
  '7 min read',
  'https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop'
),
(
  'Best Mountains to Visit in 2026',
  'best-mountains-2026',
  'From the Alps to the Himalayas, explore the most breathtaking mountain destinations for adventure seekers.',
  '<p>For adventure seekers and nature lovers, there''s nothing quite like the majesty of a mountain range. Here are our top picks for mountain destinations in 2026.</p><h2>1. The Dolomites, Italy</h2><p>Famous for their unique limestone peaks and stunning alpine meadows, the Dolomites offer incredible hiking in the summer and world-class skiing in the winter.</p><h2>2. Torres del Paine, Chile</h2><p>This Chilean national park is a dream for trekkers. Its granite towers, turquoise lakes, and vast glaciers provide a truly epic backdrop for any adventure.</p><h2>3. Banff National Park, Canada</h2><p>Banff is a year-round destination with something for everyone. From the iconic Lake Louise to the rugged peaks of the Rockies, it''s a place of unparalleled natural beauty.</p>',
  'Adventure',
  '6 min read',
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=800&auto=format&fit=crop'
),
(
  'The Art of Solo Travel: A Guide',
  'solo-travel-guide',
  'Everything you need to know about traveling alone, from safety tips to meeting new people along the way.',
  '<p>Traveling alone can be one of the most rewarding experiences of your life. It offers complete freedom, the chance to meet new people, and an opportunity for deep self-discovery.</p><h2>Start Small</h2><p>If you''re nervous about your first solo trip, start with a weekend getaway to a nearby city. This will help you build confidence before embarking on a longer journey.</p><h2>Stay in Hostels</h2><p>Hostels are great for solo travelers as they provide a social environment where it''s easy to meet other people. Many offer private rooms if you''re not ready for a dorm.</p><h2>Trust Your Instincts</h2><p>Safety is paramount when traveling alone. Trust your gut and be aware of your surroundings at all times.</p>',
  'Guide',
  '8 min read',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=800&auto=format&fit=crop'
),
(
  'Top 10 Street Foods in Southeast Asia',
  'southeast-asia-street-food',
  'A culinary journey through the vibrant markets and street stalls of Bangkok, Hanoi, and beyond.',
  '<p>Southeast Asia is a food lover''s paradise, and some of the best meals you''ll ever have will be from a street stall.</p><h2>1. Pad Thai, Thailand</h2><p>A classic for a reason. This stir-fried noodle dish is a perfect balance of sweet, sour, and savory flavors.</p><h2>2. Pho, Vietnam</h2><p>This fragrant noodle soup is a staple of Vietnamese cuisine. It''s often served with fresh herbs, lime, and chili for an extra kick.</p><h2>3. Nasi Goreng, Indonesia</h2><p>Indonesian fried rice is typically served with a fried egg on top and a side of prawn crackers. It''s simple, filling, and delicious.</p>',
  'Food',
  '10 min read',
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop'
),
(
  'Sustainable Travel: Why it Matters',
  'sustainable-travel-importance',
  'How to reduce your carbon footprint and support local communities during your next vacation.',
  '<p>As the world becomes more aware of the impact of travel on the environment, sustainable travel is more important than ever.</p><h2>Support Local Communities</h2><p>Choose locally-owned accommodation, eat at independent restaurants, and hire local guides. This ensures that your money stays within the community you''re visiting.</p><h2>Reduce Your Carbon Footprint</h2><p>Consider alternatives to flying when possible, such as trains or buses. When you do fly, consider carbon offsetting your journey.</p><h2>Respect Nature</h2><p>Stay on marked trails, dispose of waste properly, and avoid activities that exploit animals.</p>',
  'Nature',
  '6 min read',
  'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=800&auto=format&fit=crop'
)
ON CONFLICT (slug) DO NOTHING;

-- 6. Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Create home_carousel table
CREATE TABLE IF NOT EXISTS public.home_carousel (
  id uuid default gen_random_uuid() primary key,
  country text not null unique,
  region text not null,
  description text not null,
  label text not null,
  location_tag text not null,
  image_url text not null,
  bg_image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
ALTER TABLE public.home_carousel ENABLE ROW LEVEL SECURITY;

-- 3. Select policy (allow everyone to view carousel destinations)
DROP POLICY IF EXISTS "Allow public read access to home_carousel" ON public.home_carousel;
CREATE POLICY "Allow public read access to home_carousel"
  ON public.home_carousel FOR SELECT
  USING (true);

-- 4. Write policy (allow authenticated users to manage carousel)
DROP POLICY IF EXISTS "Allow authenticated users to manage home_carousel" ON public.home_carousel;
CREATE POLICY "Allow authenticated users to manage home_carousel"
  ON public.home_carousel FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 5. Seed initial carousel data
INSERT INTO public.home_carousel (country, region, description, label, location_tag, image_url, bg_image_url)
VALUES 
('Greece', 'Europe', 'Greece is famous for its iconic blue domes, ancient history, and stunning Aegean sunsets.', 'Santorini', 'Oia Village, Santorini', '/images/hero_greece_oia.png', '/images/hero_greece_oia.png'),
('Italy', 'Europe', 'Italy is known for its historic art, culinary masterpieces, and the dramatic Amalfi Coast.', 'Positano', 'Amalfi Coast, Italy', '/images/card_italy.png', '/images/card_italy.png'),
('Spain', 'Region', 'Spain is famous for its islands, beach holidays, surfing, diving and yachting.', 'Madrid', 'Plaza Mayor, Madrid', '/images/card_madrid.png', '/images/hero_seoul_night.png'),
('UAE', 'Middle East', 'UAE offers a blend of futuristic skyscrapers, luxury shopping, and desert adventures.', 'Dubai', 'Museum of the Future, Dubai', '/images/card_uae.png', '/images/hero_uae_museum.png'),
('USA', 'North America', 'USA features diverse landscapes from bustling New York streets to the Grand Canyon.', 'New York', 'Times Square, New York', '/images/card_usa.png', '/images/card_usa.png'),
('Canada', 'North America', 'Canada is renowned for its vast wilderness, stunning lakes, and friendly multicultural cities.', 'Banff', 'Moraine Lake, Banff', '/images/card_canada.png', '/images/card_canada.png'),
('Thailand', 'Asia', 'Thailand is a land of tropical beaches, ornate temples, and vibrant street life.', 'Phuket', 'Maya Bay, Phi Phi Islands', '/images/card_thailand.png', '/images/card_thailand.png'),
('Ireland', 'Europe', 'Ireland is known for its lush green landscapes, historic castles, and vibrant culture.', 'Cliffs of Moher', 'Cliffs of Moher, County Clare', '/images/why_mountains.png', '/images/why_mountains.png')
ON CONFLICT (country) DO NOTHING;

-- 6. Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Create testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  location text not null,
  quote text not null,
  avatar_url text not null,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create why_snaptrip table
CREATE TABLE IF NOT EXISTS public.why_snaptrip (
  id uuid default gen_random_uuid() primary key,
  icon text not null,
  title text not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.why_snaptrip ENABLE ROW LEVEL SECURITY;

-- 4. Select policies (public read access)
DROP POLICY IF EXISTS "Allow public read access to testimonials" ON public.testimonials;
CREATE POLICY "Allow public read access to testimonials" ON public.testimonials FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to why_snaptrip" ON public.why_snaptrip;
CREATE POLICY "Allow public read access to why_snaptrip" ON public.why_snaptrip FOR SELECT USING (true);

-- 5. Write policies (authenticated users only)
DROP POLICY IF EXISTS "Allow authenticated users to manage testimonials" ON public.testimonials;
CREATE POLICY "Allow authenticated users to manage testimonials" ON public.testimonials FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to manage why_snaptrip" ON public.why_snaptrip;
CREATE POLICY "Allow authenticated users to manage why_snaptrip" ON public.why_snaptrip FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Seed initial data
INSERT INTO public.why_snaptrip (icon, title, text)
VALUES 
('🗺️', 'Seamless and Intuitive', 'Plan your trip with ease using our clean and simple interface.'),
('⭐', 'Effortless Planning', 'Create personalized itineraries tailored to your unique travel style.'),
('⚡', 'Personalized Journeys', 'Our AI-powered engine finds the best places for your journey.'),
('💡', 'Expert Recommendations', 'Get handpicked recommendations from seasoned travelers.')
ON CONFLICT DO NOTHING;

INSERT INTO public.testimonials (name, location, quote, avatar_url, image_url)
VALUES 
('Riya Sharma', 'Dubai', 'Planning my trip was super easy and smooth. Loved the experience.', '/images/testimonial.png', '/images/testimonial.png'),
('Alex Chen', 'Tokyo', 'SnapTrip completely changed how I explore new cities. Highly recommend!', '/images/testimonial.png', '/images/explore_japan.png')
ON CONFLICT DO NOTHING;

-- 7. Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Ensure buckets are marked as public
INSERT INTO storage.buckets (id, name, public)
VALUES 
('blogs', 'blogs', true),
('carousel', 'carousel', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 2. Allow public SELECT access so uploaded images are visible on the website
DROP POLICY IF EXISTS "Public Select Blogs" ON storage.objects;
CREATE POLICY "Public Select Blogs" ON storage.objects
  FOR SELECT USING (bucket_id = 'blogs');

DROP POLICY IF EXISTS "Public Select Carousel" ON storage.objects;
CREATE POLICY "Public Select Carousel" ON storage.objects
  FOR SELECT USING (bucket_id = 'carousel');

-- 3. Allow INSERT/UPLOAD access (allows files to be uploaded from the CMS pages)
DROP POLICY IF EXISTS "Public Insert Blogs" ON storage.objects;
CREATE POLICY "Public Insert Blogs" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'blogs');

DROP POLICY IF EXISTS "Public Insert Carousel" ON storage.objects;
CREATE POLICY "Public Insert Carousel" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'carousel');

-- 4. Allow UPDATE and DELETE access so you can edit and clean up files
DROP POLICY IF EXISTS "Public Update Blogs" ON storage.objects;
CREATE POLICY "Public Update Blogs" ON storage.objects
  FOR UPDATE USING (bucket_id = 'blogs');

DROP POLICY IF EXISTS "Public Delete Blogs" ON storage.objects;
CREATE POLICY "Public Delete Blogs" ON storage.objects
  FOR DELETE USING (bucket_id = 'blogs');

DROP POLICY IF EXISTS "Public Update Carousel" ON storage.objects;
CREATE POLICY "Public Update Carousel" ON storage.objects
  FOR UPDATE USING (bucket_id = 'carousel');

DROP POLICY IF EXISTS "Public Delete Carousel" ON storage.objects;
CREATE POLICY "Public Delete Carousel" ON storage.objects
  FOR DELETE USING (bucket_id = 'carousel');
-- Add demo fields to how_it_works_settings table
ALTER TABLE public.how_it_works_settings 
ADD COLUMN IF NOT EXISTS demo_i_time_1 text not null default '08',
ADD COLUMN IF NOT EXISTS demo_i_label_1 text not null default 'MORNING ARRIVAL',
ADD COLUMN IF NOT EXISTS demo_i_title_1 text not null default 'Tokyo Narita Express',
ADD COLUMN IF NOT EXISTS demo_i_price_1 text not null default '$32.00',
ADD COLUMN IF NOT EXISTS demo_i_desc_1 text not null default 'Direct transfer to Shinjuku. Our concierge has pre-booked your green car seats for maximum comfort.',
ADD COLUMN IF NOT EXISTS demo_i_tags_1 text not null default 'TRANSPORT, PRE-PAID',
ADD COLUMN IF NOT EXISTS demo_i_time_2 text not null default '13',
ADD COLUMN IF NOT EXISTS demo_i_label_2 text not null default 'LUNCH ENGAGEMENT',
ADD COLUMN IF NOT EXISTS demo_i_title_2 text not null default 'Kozue, Park Hyatt',
ADD COLUMN IF NOT EXISTS demo_i_price_2 text not null default '$120.00',
ADD COLUMN IF NOT EXISTS demo_i_desc_2 text not null default 'Contemporary Japanese dining with views across the Tokyo skyline. Window table confirmed.',
ADD COLUMN IF NOT EXISTS demo_i_img_2 text not null default '/images/how_food.png',
ADD COLUMN IF NOT EXISTS demo_i_ai_suggestion text not null default 'Based on current weather, we recommend visiting the Gyoen Garden at 4:00 PM for optimal lighting.',
ADD COLUMN IF NOT EXISTS demo_map_placeholder text not null default 'Live Map Visualization',
ADD COLUMN IF NOT EXISTS demo_support_placeholder text not null default '24/7 Concierge Support';

-- Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Create explore_settings table
CREATE TABLE IF NOT EXISTS public.explore_settings (
  id text primary key default 'default',
  hero_tagline text not null,
  hero_title text not null,
  quote_text text not null,
  quote_author text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 'default')
);

-- 2. Create country_guides table
CREATE TABLE IF NOT EXISTS public.country_guides (
  id text primary key, -- e.g. 'japan', 'italy'
  name text not null,
  "desc" text not null,
  tag text not null,
  hero_img text not null,
  is_featured boolean not null default false,
  capital text not null,
  currency text not null,
  language text not null,
  time_zone text not null,
  best_time text not null,
  emergency_police text not null,
  emergency_ambulance text not null,
  emergency_embassy text not null,
  experience_title text not null,
  experience_desc text not null,
  experience_img text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create country_guide_cards table
CREATE TABLE IF NOT EXISTS public.country_guide_cards (
  id uuid default gen_random_uuid() primary key,
  country_id text references public.country_guides(id) ON DELETE CASCADE not null,
  icon_name text not null, -- 'about', 'snapshot', 'clock'
  title text not null,
  "desc" text not null,
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create country_guide_items table
CREATE TABLE IF NOT EXISTS public.country_guide_items (
  id uuid default gen_random_uuid() primary key,
  country_id text references public.country_guides(id) ON DELETE CASCADE not null,
  type text not null, -- 'connectivity' or 'etiquette'
  title text not null,
  "desc" text not null,
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Create country_guide_cities table
CREATE TABLE IF NOT EXISTS public.country_guide_cities (
  id uuid default gen_random_uuid() primary key,
  country_id text references public.country_guides(id) ON DELETE CASCADE not null,
  name text not null,
  "desc" text not null,
  img_url text not null,
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.explore_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_guide_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_guide_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.country_guide_cities ENABLE ROW LEVEL SECURITY;

-- 7. Select policies (public read access)
DROP POLICY IF EXISTS "Allow public read access to explore_settings" ON public.explore_settings;
CREATE POLICY "Allow public read access to explore_settings" ON public.explore_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to country_guides" ON public.country_guides;
CREATE POLICY "Allow public read access to country_guides" ON public.country_guides FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to country_guide_cards" ON public.country_guide_cards;
CREATE POLICY "Allow public read access to country_guide_cards" ON public.country_guide_cards FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to country_guide_items" ON public.country_guide_items;
CREATE POLICY "Allow public read access to country_guide_items" ON public.country_guide_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to country_guide_cities" ON public.country_guide_cities;
CREATE POLICY "Allow public read access to country_guide_cities" ON public.country_guide_cities FOR SELECT USING (true);

-- 8. Write policies (authenticated users only)
DROP POLICY IF EXISTS "Allow auth manage explore_settings" ON public.explore_settings;
CREATE POLICY "Allow auth manage explore_settings" ON public.explore_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow auth manage country_guides" ON public.country_guides;
CREATE POLICY "Allow auth manage country_guides" ON public.country_guides FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow auth manage country_guide_cards" ON public.country_guide_cards;
CREATE POLICY "Allow auth manage country_guide_cards" ON public.country_guide_cards FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow auth manage country_guide_items" ON public.country_guide_items;
CREATE POLICY "Allow auth manage country_guide_items" ON public.country_guide_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow auth manage country_guide_cities" ON public.country_guide_cities;
CREATE POLICY "Allow auth manage country_guide_cities" ON public.country_guide_cities FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 9. Seed initial Explore settings
INSERT INTO public.explore_settings (id, hero_tagline, hero_title, quote_text, quote_author)
VALUES (
  'default',
  'Explore the Unseen',
  'Where will your curiosity lead you next?',
  'The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.',
  'MARCEL PROUST'
)
ON CONFLICT (id) DO NOTHING;

-- 10. Seed initial Country Guides
INSERT INTO public.country_guides (id, name, "desc", tag, hero_img, is_featured, capital, currency, language, time_zone, best_time, emergency_police, emergency_ambulance, emergency_embassy, experience_title, experience_desc, experience_img)
VALUES 
(
  'japan',
  'Japan',
  'A harmonious blend of ancient traditions and futuristic innovation. From the neon-lit streets of Tokyo to the tranquil temples of Kyoto, Japan offers a sensory journey unlike any other.',
  'Culture',
  '/images/explore_japan.png',
  true,
  'Tokyo',
  'Yen (¥)',
  'Japanese',
  'GMT+9',
  'Mar - May',
  '110',
  '119',
  'Contact your local embassy or consulate for specific assistance.',
  'Traditional Tea Ceremony',
  'Experience the mindful preparation of matcha and the profound hospitality of Japanese culture.',
  '/images/explore_japan.png'
),
(
  'italy',
  'Italy',
  'The ultimate guide to the rolling hills, hidden vineyards, and the slow life of the Italian countryside.',
  'Editorial',
  '/images/guide_italy.png',
  true,
  'Rome',
  'Euro (€)',
  'Italian',
  'GMT+1',
  'Apr - Jun',
  '113',
  '118',
  'Contact your local embassy or consulate for specific assistance.',
  'Tuscan Wine Tasting',
  'Indulge in authentic winemaking tours and tasting inside historic medieval cellars.',
  '/images/guide_italy.png'
),
(
  'morocco',
  'Morocco',
  'Exploring the vibrant souks of Marrakesh and the blue-washed walls of Chefchaouen.',
  'Lifestyle',
  '/images/guide_morocco.png',
  true,
  'Rabat',
  'Dirham (MAD)',
  'Arabic, Berber',
  'GMT+1',
  'Mar - May',
  '19',
  '15',
  'Contact your local embassy or consulate for specific assistance.',
  'Marrakesh Souk Tour',
  'Navigate the rich, spice-filled alleys and artisan markets with a licensed local guide.',
  '/images/guide_morocco.png'
),
(
  'france',
  'France',
  'Journeying through the lavender fields of Provence and the rugged coastline of Brittany.',
  'Vintage',
  '/images/guide_france.png',
  true,
  'Paris',
  'Euro (€)',
  'French',
  'GMT+1',
  'May - Sep',
  '17',
  '15',
  'Contact your local embassy or consulate for specific assistance.',
  'Seine Sunset Cruise',
  'Sail along Paris'' famous river landmarks while enjoying fine cheese and wine.',
  '/images/guide_france.png'
)
ON CONFLICT (id) DO NOTHING;

-- 11. Seed initial Country Guide Cards (Japan)
INSERT INTO public.country_guide_cards (country_id, icon_name, title, "desc", display_order)
VALUES 
  ('japan', 'about', 'About', 'An archipelago of over 6,000 islands, Japan''s topography ranges from snow-capped peaks to tropical beaches, defined by deep spiritual roots.', 0),
  ('japan', 'snapshot', 'Travel Snapshot', 'Efficiency meets elegance. Navigate with ease using the Shinkansen, indulge in world-class culinary delights, and find peace in Zen gardens.', 1),
  ('japan', 'clock', 'Best Time to Visit', 'Spring for Sakura blossoms and Autumn for fiery maple leaves are peak seasons. Winter offers world-class skiing in Hokkaido.', 2),
  ('italy', 'about', 'About', 'Rich history, majestic architecture, and culinary brilliance define the cradle of the Renaissance.', 0),
  ('italy', 'snapshot', 'Travel Snapshot', 'Savor world-class pasta, navigate romantic canal towns, and enjoy relaxed evening strolls.', 1),
  ('italy', 'clock', 'Best Time to Visit', 'Spring and Autumn are the best seasons for scenic country touring with mild weather.', 2)
ON CONFLICT DO NOTHING;

-- 12. Seed initial Country Guide Items (Japan)
INSERT INTO public.country_guide_items (country_id, type, title, "desc", display_order)
VALUES 
  ('japan', 'connectivity', 'SIM Cards', 'Purchase data SIM cards or rent pocket Wi-Fi at airports.', 0),
  ('japan', 'connectivity', 'Transportation', 'Use Japan Rail (JR) Pass for intercity travel and Suica/Pasmo for local transit.', 1),
  ('japan', 'etiquette', 'Greetings', 'Bowing is the customary greeting. Handshakes are also common in business.', 0),
  ('japan', 'etiquette', 'Footwear', 'Take off your shoes when entering homes, ryokans, and some traditional restaurants.', 1),
  ('japan', 'etiquette', 'Tipping', 'Do not tip in restaurants or taxis; excellent service is standard.', 2)
ON CONFLICT DO NOTHING;

-- 13. Seed initial Country Guide Cities (Japan)
INSERT INTO public.country_guide_cities (country_id, name, "desc", img_url, display_order)
VALUES 
  ('japan', 'Tokyo', 'Vibrant metropolis blending neon lights and historic shrines.', '/images/hero_city.png', 0),
  ('japan', 'Kyoto', 'Cultural heart with thousands of classical Buddhist temples.', '/images/coastal_beach.png', 1),
  ('japan', 'Osaka', 'A dynamic port city known for modern architecture and hearty street food.', '/images/marrakech.png', 2)
ON CONFLICT DO NOTHING;

-- 14. Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Create footer_settings table
CREATE TABLE IF NOT EXISTS public.footer_settings (
  id text primary key default 'default',
  description text not null,
  phone text not null,
  email text not null,
  facebook_url text,
  twitter_url text,
  instagram_url text,
  youtube_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 'default')
);

-- 2. Create footer_links table
CREATE TABLE IF NOT EXISTS public.footer_links (
  id uuid default gen_random_uuid() primary key,
  label text not null,
  url text not null,
  category text not null, -- 'Quick Links', 'Support', or custom headings
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.footer_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.footer_links ENABLE ROW LEVEL SECURITY;

-- 4. Select policies (public read access)
DROP POLICY IF EXISTS "Allow public read access to footer_settings" ON public.footer_settings;
CREATE POLICY "Allow public read access to footer_settings" ON public.footer_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to footer_links" ON public.footer_links;
CREATE POLICY "Allow public read access to footer_links" ON public.footer_links FOR SELECT USING (true);

-- 5. Write policies (authenticated users only)
DROP POLICY IF EXISTS "Allow authenticated users to manage footer_settings" ON public.footer_settings;
CREATE POLICY "Allow authenticated users to manage footer_settings" ON public.footer_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to manage footer_links" ON public.footer_links;
CREATE POLICY "Allow authenticated users to manage footer_links" ON public.footer_links FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Seed initial footer settings
INSERT INTO public.footer_settings (id, description, phone, email, facebook_url, twitter_url, instagram_url, youtube_url)
VALUES (
  'default',
  'Simplifying the way you plan, organize, and experience travel — so you can focus on what truly matters: the journey.',
  '(123) 456-7890',
  'ABC@gmail.com',
  '#',
  '#',
  '#',
  '#'
)
ON CONFLICT (id) DO NOTHING;

-- 7. Seed initial footer links
INSERT INTO public.footer_links (label, url, category, display_order)
VALUES 
  ('Plan Your Trip', '/plan', 'Quick Links', 0),
  ('How it works', '/how-it-works', 'Quick Links', 1),
  ('Why Us', '/why-us', 'Quick Links', 2),
  ('Testimonial', '/testimonials', 'Quick Links', 3),
  ('Blog', '/blog', 'Quick Links', 4),
  ('Privacy Policy', '/privacy', 'Support', 0),
  ('Terms Of Use', '/terms', 'Support', 1)
ON CONFLICT DO NOTHING;

-- 8. Force schema reload
NOTIFY pgrst, 'reload schema';
-- 1. Create how_it_works_settings table
CREATE TABLE IF NOT EXISTS public.how_it_works_settings (
  id text primary key default 'default',
  hero_badge text not null,
  hero_title text not null,
  hero_description text not null,
  planning_title text not null,
  how_works_title text not null,
  how_works_desc text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint single_row check (id = 'default')
);

-- 2. Create how_it_works_steps table
CREATE TABLE IF NOT EXISTS public.how_it_works_steps (
  id uuid default gen_random_uuid() primary key,
  type text not null, -- 'planning' or 'how'
  step_number text not null, -- '01', '02', etc.
  title text not null,
  description text not null,
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.how_it_works_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.how_it_works_steps ENABLE ROW LEVEL SECURITY;

-- 4. Select policies (public read access)
DROP POLICY IF EXISTS "Allow public read access to how_it_works_settings" ON public.how_it_works_settings;
CREATE POLICY "Allow public read access to how_it_works_settings" ON public.how_it_works_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access to how_it_works_steps" ON public.how_it_works_steps;
CREATE POLICY "Allow public read access to how_it_works_steps" ON public.how_it_works_steps FOR SELECT USING (true);

-- 5. Write policies (authenticated users only)
DROP POLICY IF EXISTS "Allow authenticated users to manage how_it_works_settings" ON public.how_it_works_settings;
CREATE POLICY "Allow authenticated users to manage how_it_works_settings" ON public.how_it_works_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to manage how_it_works_steps" ON public.how_it_works_steps;
CREATE POLICY "Allow authenticated users to manage how_it_works_steps" ON public.how_it_works_steps FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Seed initial general page settings
INSERT INTO public.how_it_works_settings (id, hero_badge, hero_title, hero_description, planning_title, how_works_title, how_works_desc)
VALUES (
  'default',
  'INTRODUCING ATLAS LUMINA',
  'Crafting Your Next Odyssey.',
  'A fusion of high-end editorial curation and artificial intelligence. SnapTrip transforms wandering into precision exploration.',
  'The Art of Seamless Planning',
  'How It Works',
  'Snaptrip guides you through every step of your travel planning — from discovering destinations to creating a personalized itinerary. With simple tools and smart suggestions, you can plan your perfect trip quickly and without stress.'
)
ON CONFLICT (id) DO NOTHING;

-- 7. Seed initial page steps (Art of Planning + Timeline walkthrough)
INSERT INTO public.how_it_works_steps (type, step_number, title, description, display_order)
VALUES 
  -- Planning steps
  ('planning', '01', 'Define Your Muse', 'Tell our AI your desired mood—whether it''s the quiet zen of Kyoto or the kinetic pulse of Berlin.', 0),
  ('planning', '02', 'Curated Logic', 'We calculate flight windows, seasonal shifts, and cultural events to anchor your dates perfectly.', 1),
  ('planning', '03', 'Dynamic Refinement', 'Your itinerary lives and breathes. Adjust one stop, and our system re-optimizes your entire journey.', 2),
  
  -- Walkthrough steps
  ('how', '01', 'Pick your destination', 'Search 10,000+ destinations. See trending spots, seasonal highlights.', 0),
  ('how', '02', 'Choose your travel style', 'Adventure, culture, or food tour? Tell us your vibe.', 1),
  ('how', '03', 'Set duration & budget', 'Pick travel dates and a daily budget auto-calculated.', 2),
  ('how', '04', 'Select attractions', 'Browse curated must-sees and hidden gems.', 3),
  ('how', '05', 'Itinerary Complete!', 'Download your full plan maps and bookings.', 4)
ON CONFLICT DO NOTHING;

-- 8. Force schema reload
NOTIFY pgrst, 'reload schema';
CREATE TABLE IF NOT EXISTS public.user_city_ratings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    ratings JSONB NOT NULL DEFAULT '{}'::jsonb,
    average_score NUMERIC(3, 1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, city)
);

-- RLS Policies
ALTER TABLE public.user_city_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own city ratings" 
ON public.user_city_ratings FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own city ratings" 
ON public.user_city_ratings FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own city ratings" 
ON public.user_city_ratings FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own city ratings" 
ON public.user_city_ratings FOR DELETE 
USING (auth.uid() = user_id);
-- Add hero_bg_image to explore_settings
ALTER TABLE public.explore_settings
ADD COLUMN IF NOT EXISTS hero_bg_image text DEFAULT '/images/guide_hero.png';
-- Add hero_bg_image to how_it_works_settings
ALTER TABLE public.how_it_works_settings
ADD COLUMN IF NOT EXISTS hero_bg_image text DEFAULT '/images/how_hero.png';
-- Add hero_bg_image to how_it_works_settings
ALTER TABLE public.how_it_works_settings
ADD COLUMN IF NOT EXISTS hero_bg_image text DEFAULT '/images/how_hero.png';
-- Add totalScore to places
ALTER TABLE public.places
ADD COLUMN IF NOT EXISTS "totalScore" double precision;
-- 1. Create pages table for CMS
CREATE TABLE IF NOT EXISTS public.pages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    slug text UNIQUE NOT NULL,
    title text NOT NULL,
    content text,
    meta_description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create contact_messages table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    subject text NOT NULL,
    message text NOT NULL,
    status text DEFAULT 'unread' NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Policies for pages
DROP POLICY IF EXISTS "Allow public read access to pages" ON public.pages;
CREATE POLICY "Allow public read access to pages" ON public.pages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to manage pages" ON public.pages;
CREATE POLICY "Allow authenticated users to manage pages" ON public.pages FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policies for contact_messages
DROP POLICY IF EXISTS "Allow public to insert messages" ON public.contact_messages;
CREATE POLICY "Allow public to insert messages" ON public.contact_messages FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to manage messages" ON public.contact_messages;
CREATE POLICY "Allow authenticated users to manage messages" ON public.contact_messages FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert default CMS pages
INSERT INTO public.pages (slug, title, content, meta_description) VALUES
('privacy', 'Privacy Policy', '<p>Your privacy policy content goes here.</p>', 'Our Privacy Policy'),
('terms', 'Terms of Use', '<p>Your terms of use content goes here.</p>', 'Our Terms of Use')
ON CONFLICT (slug) DO NOTHING;
-- Create published_places table matching places schema exactly

CREATE TABLE IF NOT EXISTS published_places (
  id bigint PRIMARY KEY,
  "country" text NOT NULL,
  "city" text,
  "website" text,
  "title" text,
  "subTitle" text,
  "reviewsCount" bigint,
  "totalScore" double precision,
  "postalCode" text,
  "phone" text,
  "description" text,
  "categoryName" text,
  "address" text,
  "image_url" text,
  
  -- Location
  "location_lat" double precision,
  "location_lng" double precision,

  -- Opening Hours (0-6)
  "openingHours_0_day" text, "openingHours_0_hours" text,
  "openingHours_1_day" text, "openingHours_1_hours" text,
  "openingHours_2_day" text, "openingHours_2_hours" text,
  "openingHours_3_day" text, "openingHours_3_hours" text,
  "openingHours_4_day" text, "openingHours_4_hours" text,
  "openingHours_5_day" text, "openingHours_5_hours" text,
  "openingHours_6_day" text, "openingHours_6_hours" text,

  -- Accessibility (ai_Acc)
  "ai_Acc_0_entrance" boolean, "ai_Acc_1_entrance" boolean, "ai_Acc_2_entrance" boolean, "ai_Acc_3_entrance" boolean, "ai_Acc_4_entrance" boolean,
  "ai_Acc_0_parking" boolean, "ai_Acc_1_parking" boolean, "ai_Acc_2_parking" boolean, "ai_Acc_3_parking" boolean, "ai_Acc_4_parking" boolean,
  "ai_Acc_0_restroom" boolean, "ai_Acc_1_restroom" boolean, "ai_Acc_2_restroom" boolean, "ai_Acc_3_restroom" boolean, "ai_Acc_4_restroom" boolean,

  -- Children (ai_Chld)
  "ai_Chld_0_kids" boolean, "ai_Chld_1_kids" boolean, "ai_Chld_2_kids" boolean, "ai_Chld_3_kids" boolean,

  -- Crowd (ai_Crwd)
  "ai_Crwd_0_lgbtq" boolean, "ai_Crwd_1_lgbtq" boolean, "ai_Crwd_2_lgbtq" boolean, "ai_Crwd_3_lgbtq" boolean,

  -- Pets (ai_Pets)
  "ai_Pets_0_dogs" boolean, "ai_Pets_1_dogs" boolean, "ai_Pets_2_dogs" boolean,

  -- Planning (ai_Plan)
  "ai_Plan_0_tickets" boolean, "ai_Plan_1_tickets" boolean, "ai_Plan_2_tickets" boolean, "ai_Plan_3_tickets" boolean,

  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  UNIQUE("title", "address")
);

CREATE INDEX IF NOT EXISTS idx_published_places_country ON published_places("country");
CREATE INDEX IF NOT EXISTS idx_published_places_city ON published_places("city");

NOTIFY pgrst, 'reload schema';
ALTER TABLE public.contact_messages ADD COLUMN IF NOT EXISTS phone text;
-- Update the handle_new_user trigger function to auto-generate a username if missing
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  base_username text;
  new_username text;
  counter int := 1;
BEGIN
  -- Determine base username
  -- If full_name exists (OAuth), clean it. Else use the first part of the email.
  IF new.raw_user_meta_data->>'username' IS NOT NULL THEN
    new_username := lower(new.raw_user_meta_data->>'username');
  ELSIF new.raw_user_meta_data->>'full_name' IS NOT NULL THEN
    base_username := lower(regexp_replace(new.raw_user_meta_data->>'full_name', '[^a-zA-Z0-9]', '', 'g'));
    -- Ensure at least 3 characters
    IF length(base_username) < 3 THEN
      base_username := base_username || 'user';
    END IF;
    new_username := base_username;
  ELSE
    base_username := lower(split_part(new.email, '@', 1));
    base_username := regexp_replace(base_username, '[^a-zA-Z0-9]', '', 'g');
    IF length(base_username) < 3 THEN
      base_username := base_username || 'user';
    END IF;
    new_username := base_username;
  END IF;

  -- Ensure uniqueness
  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE username = new_username) LOOP
    new_username := base_username || counter::text;
    counter := counter + 1;
  END LOOP;

  INSERT INTO public.profiles (id, full_name, avatar_url, email, username)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url',
    new.email,
    new_username
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    updated_at = NOW();
    
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- Add stay_time column to places
ALTER TABLE public.places ADD COLUMN IF NOT EXISTS stay_time text;

-- Add stay_time column to published_places
ALTER TABLE public.published_places ADD COLUMN IF NOT EXISTS stay_time text;

-- Force schema reload
NOTIFY pgrst, 'reload schema';
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS policies
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (for the API to work if it uses anon key, though the API currently uses service_role key)
CREATE POLICY "Allow public insert" ON public.newsletter_subscribers
    FOR INSERT WITH CHECK (true);

-- Allow admins to read
CREATE POLICY "Allow admins to select" ON public.newsletter_subscribers
    FOR SELECT USING (
        auth.role() = 'authenticated'
    );
-- Create user_country_logs table
CREATE TABLE IF NOT EXISTS public.user_country_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    country TEXT NOT NULL,
    photo_url TEXT,
    ratings JSONB NOT NULL DEFAULT '{}'::jsonb,
    average_score NUMERIC(3, 1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, country)
);

-- RLS Policies for user_country_logs
ALTER TABLE public.user_country_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own country logs" 
ON public.user_country_logs FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own country logs" 
ON public.user_country_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own country logs" 
ON public.user_country_logs FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own country logs" 
ON public.user_country_logs FOR DELETE USING (auth.uid() = user_id);

-- Create user_city_logs table
CREATE TABLE IF NOT EXISTS public.user_city_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, country, city)
);

-- RLS Policies for user_city_logs
ALTER TABLE public.user_city_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own city logs" 
ON public.user_city_logs FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own city logs" 
ON public.user_city_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own city logs" 
ON public.user_city_logs FOR DELETE USING (auth.uid() = user_id);

-- Create travel_photos bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('travel_photos', 'travel_photos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for travel_photos
CREATE POLICY "Public Access for travel_photos"
ON storage.objects FOR SELECT
USING ( bucket_id = 'travel_photos' );

CREATE POLICY "Authenticated users can upload travel_photos"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'travel_photos' AND auth.role() = 'authenticated' );

CREATE POLICY "Users can update their own travel_photos"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'travel_photos' AND auth.uid() = owner )
WITH CHECK ( bucket_id = 'travel_photos' AND auth.uid() = owner );

CREATE POLICY "Users can delete their own travel_photos"
ON storage.objects FOR DELETE
USING ( bucket_id = 'travel_photos' AND auth.uid() = owner );

-- Force schema reload
NOTIFY pgrst, 'reload schema';
-- FRESH START: Drop and Recreate the places table (QUOTED VERSION)
-- This version uses double quotes to preserve case-sensitivity (camelCase)

DROP TABLE IF EXISTS places;

CREATE TABLE places (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" text NOT NULL,
  "city" text,
  "website" text,
  "title" text,
  "subTitle" text,
  "reviewsCount" bigint,
  "postalCode" text,
  "phone" text,
  "description" text,
  "categoryName" text,
  "address" text,
  "image_url" text,
  
  -- Location
  "location_lat" double precision,
  "location_lng" double precision,

  -- Opening Hours (0-6)
  "openingHours_0_day" text, "openingHours_0_hours" text,
  "openingHours_1_day" text, "openingHours_1_hours" text,
  "openingHours_2_day" text, "openingHours_2_hours" text,
  "openingHours_3_day" text, "openingHours_3_hours" text,
  "openingHours_4_day" text, "openingHours_4_hours" text,
  "openingHours_5_day" text, "openingHours_5_hours" text,
  "openingHours_6_day" text, "openingHours_6_hours" text,

  -- Accessibility (ai_Acc)
  "ai_Acc_0_entrance" boolean, "ai_Acc_1_entrance" boolean, "ai_Acc_2_entrance" boolean, "ai_Acc_3_entrance" boolean, "ai_Acc_4_entrance" boolean,
  "ai_Acc_0_parking" boolean, "ai_Acc_1_parking" boolean, "ai_Acc_2_parking" boolean, "ai_Acc_3_parking" boolean, "ai_Acc_4_parking" boolean,
  "ai_Acc_0_restroom" boolean, "ai_Acc_1_restroom" boolean, "ai_Acc_2_restroom" boolean, "ai_Acc_3_restroom" boolean, "ai_Acc_4_restroom" boolean,

  -- Children (ai_Chld)
  "ai_Chld_0_kids" boolean, "ai_Chld_1_kids" boolean, "ai_Chld_2_kids" boolean, "ai_Chld_3_kids" boolean,

  -- Crowd (ai_Crwd)
  "ai_Crwd_0_lgbtq" boolean, "ai_Crwd_1_lgbtq" boolean, "ai_Crwd_2_lgbtq" boolean, "ai_Crwd_3_lgbtq" boolean,

  -- Pets (ai_Pets)
  "ai_Pets_0_dogs" boolean, "ai_Pets_1_dogs" boolean, "ai_Pets_2_dogs" boolean,

  -- Planning (ai_Plan)
  "ai_Plan_0_tickets" boolean, "ai_Plan_1_tickets" boolean, "ai_Plan_2_tickets" boolean, "ai_Plan_3_tickets" boolean,

  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  UNIQUE("title", "address")
);

-- Index for country searches
CREATE INDEX idx_places_country ON places("country");
CREATE INDEX idx_places_city ON places("city");

-- FORCE SCHEMA RELOAD (Crucial for PostgREST cache)
NOTIFY pgrst, 'reload schema';
