-- Migration to create the places table for Google Places sync

create table if not exists places (
  id bigint generated by default as identity primary key,
  country text not null,
  city text,
  website text,
  title text,
  "subTitle" text,
  "reviewsCount" bigint,
  "postalCode" text,
  phone text,
  description text,
  "categoryName" text,
  address text,
  
  -- Location
  location_lat double precision,
  location_lng double precision,

  -- Opening Hours (0-6)
  openingHours_0_day text, openingHours_0_hours text,
  openingHours_1_day text, openingHours_1_hours text,
  openingHours_2_day text, openingHours_2_hours text,
  openingHours_3_day text, openingHours_3_hours text,
  openingHours_4_day text, openingHours_4_hours text,
  openingHours_5_day text, openingHours_5_hours text,
  openingHours_6_day text, openingHours_6_hours text,

  -- Accessibility (0-4)
  "additionalInfo_Accessibility_0_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_entrance" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_entrance" boolean,
  
  "additionalInfo_Accessibility_0_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_parking_lot" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_parking_lot" boolean,
  
  "additionalInfo_Accessibility_0_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_1_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_2_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_3_Wheelchair_accessible_restroom" boolean,
  "additionalInfo_Accessibility_4_Wheelchair_accessible_restroom" boolean,

  -- Children (0-3)
  "additionalInfo_Children_0_Good_for_kids" boolean,
  "additionalInfo_Children_1_Good_for_kids" boolean,
  "additionalInfo_Children_2_Good_for_kids" boolean,
  "additionalInfo_Children_3_Good_for_kids" boolean,

  -- Crowd (0-3)
  "additionalInfo_Crowd_0_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_1_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_2_LGBTQ+_friendly" boolean,
  "additionalInfo_Crowd_3_LGBTQ+_friendly" boolean,

  -- Pets (0-2)
  "additionalInfo_Pets_0_Dogs_allowed" boolean,
  "additionalInfo_Pets_1_Dogs_allowed" boolean,
  "additionalInfo_Pets_2_Dogs_allowed" boolean,

  -- Planning (0-3)
  "additionalInfo_Planning_0_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_1_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_2_Getting_tickets_in_advance_recommended" boolean,
  "additionalInfo_Planning_3_Getting_tickets_in_advance_recommended" boolean,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Ensure unique title and address to prevent duplicates
  unique(title, address)
);

-- Index for country searches
create index if not exists idx_places_country on places(country);
create index if not exists idx_places_city on places(city);
